# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 10:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_reference_number_required',
            field=models.BooleanField(default=False, verbose_name='reference number'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='reference_number_prefix',
            field=models.CharField(max_length=3, null=True, verbose_name='reference number prefix'),
        ),
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='language',
            field=models.CharField(choices=[('en', 'en')], max_length=5, verbose_name='language'),
        ),
    ]
