# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-07-24 14:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationcollection',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moderationcollection',
            name='date_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
