# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-12 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.migrations.operations.special


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:

# djangocms_moderation.migrations.0002_auto_20180405_1123
def gen_ref_number_existing_requests(apps, schema_editor):
    PageModerationRequestModel = apps.get_model('djangocms_moderation', 'PageModerationRequest')
    for index, request in enumerate(PageModerationRequestModel.objects.all()):
        request.reference_number = request.pk
        request.save()


class Migration(migrations.Migration):

    replaces = [('djangocms_moderation', '0002_auto_20180405_1123'), ('djangocms_moderation', '0003_auto_20180405_1311'), ('djangocms_moderation', '0004_auto_20180410_1138')]

    dependencies = [
        ('djangocms_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=14, null=True),
        ),
        migrations.AddField(
            model_name='workflow',
            name='is_reference_number_required',
            field=models.BooleanField(default=False, verbose_name='reference number'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='reference_number_prefix',
            field=models.CharField(max_length=3, null=True, verbose_name='reference number prefix'),
        ),
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='language',
            field=models.CharField(choices=[('en', 'en')], max_length=5, verbose_name='language'),
        ),
        migrations.RunPython(
            gen_ref_number_existing_requests,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=14, unique=True),
        ),
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
