# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-03 11:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_versioning', '0010_version_proxies'),
        ('djangocms_moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moderationrequest',
            name='version',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='djangocms_versioning.Version'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='moderationrequest',
            unique_together=set([('collection', 'version')]),
        ),
        migrations.RemoveField(
            model_name='moderationrequest',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='moderationrequest',
            name='object_id',
        ),
    ]
