# Generated by Django 1.11.13 on 2018-09-05 10:52
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("djangocms_moderation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollectionComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
                (
                    "collection",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="djangocms_moderation.ModerationCollection",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.CreateModel(
            name="RequestComment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True, verbose_name="message")),
                ("date_created", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="author",
                    ),
                ),
            ],
            options={"abstract": False},
        ),
        migrations.AlterModelOptions(
            name="moderationrequest",
            options={
                "ordering": ["id"],
                "verbose_name": "Request",
                "verbose_name_plural": "Requests",
            },
        ),
        migrations.AddField(
            model_name="requestcomment",
            name="moderation_request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="djangocms_moderation.ModerationRequest",
            ),
        ),
    ]
