# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-05 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0002_auto_20180405_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=14, unique=True),
        ),
    ]
