# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-14 14:16
from __future__ import unicode_literals

from django.db import migrations, models

from djangocms_moderation.constants import ACTION_CHOICES


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0003_auto_20180420_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemoderationrequestaction',
            name='action',
            field=models.CharField(choices=ACTION_CHOICES, max_length=30, verbose_name='status'),
        ),
    ]
