# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-02 13:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aldryn_forms', '0011_auto_20180110_1300'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cms', '0020_old_tree_cleanup'),
        ('djangocms_moderation', '0003_auto_20180420_0813'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageModerationRequestActionFormSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='aldryn_forms.FormSubmission', verbose_name='action form')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='by user')),
                ('for_step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='djangocms_moderation.WorkflowStep', verbose_name='for step')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='form_submission_actions', to='djangocms_moderation.PageModerationRequest', verbose_name='request')),
            ],
            options={
                'verbose_name': 'Action Form Submission',
                'verbose_name_plural': 'Action Form Submissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='approval_form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='cms.Page', verbose_name='approval form'),
        ),
    ]
