# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 09:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0003_auto_20180724_1521'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moderationcollection',
            name='is_locked',
        ),
        migrations.AddField(
            model_name='moderationcollection',
            name='status',
            field=models.TextField(choices=[('Open', 'Open'), ('In review', 'In Review'), ('Archived', 'Archived')], default='Open'),
        ),
    ]
