# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-10 10:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0003_auto_20180405_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
