# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-12 13:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0004_auto_20180412_1259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='is_reference_number_required',
        ),
    ]
