# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-09 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0004_auto_20180809_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationcollection',
            name='status',
            field=models.CharField(choices=[('CO', 'Open'), ('IR', 'In Review'), ('AR', 'Archived')], default='CO', max_length=2),
        ),
    ]
