# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-04-16 16:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0005_remove_workflow_is_reference_number_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagemoderation',
            name='disable_moderation',
        ),
        migrations.AddField(
            model_name='pagemoderation',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='enable moderation for page'),
        ),
        migrations.AlterField(
            model_name='pagemoderation',
            name='grant_on',
            field=models.IntegerField(choices=[(1, 'Current page'), (2, 'Page children (immediate)'), (3, 'Page and children (immediate)'), (4, 'Page descendants'), (5, 'Page and descendants')], default=5, verbose_name='grant on'),
        ),
        migrations.AlterField(
            model_name='pagemoderation',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='djangocms_moderation.Workflow', verbose_name='workflow'),
        ),
    ]
