# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 10:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0005_remove_workflow_is_reference_number_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workflow',
            name='reference_number_prefix',
        ),
        migrations.AddField(
            model_name='workflow',
            name='reference_number_backend',
            field=models.CharField(choices=[('Default', 'djangocms_moderation.backends.defaultWorkflowReferenceNumberBackend')], default='Default', max_length=255),
        ),
    ]
