# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 15:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0005_auto_20180924_1433'),
        ('djangocms_moderation', '0005_auto_20180919_1348'),
    ]

    operations = [

    ]
