# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 15:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0006_auto_20180618_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemoderationrequest',
            old_name='reference_number',
            new_name='compliance_number',
        ),
        migrations.RenameField(
            model_name='workflow',
            old_name='reference_number_backend',
            new_name='compliance_number_backend',
        ),
    ]
