# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-26 09:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0006_auto_20180618_2102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pagemoderationrequestaction',
            old_name='is_stale',
            new_name='is_archived',
        ),
    ]
