# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-04-16 12:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0006_auto_20180416_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagemoderationrequest',
            name='reference_number',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
