# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-25 16:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0006_merge_20180925_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcollection',
            options={'permissions': (('can_haz_cheeseburger', 'can haz cheeseburger'),)},
        ),
    ]
