# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-29 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0007_auto_20180629_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='identifier',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
