# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-28 08:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0007_auto_20180925_1704'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcollection',
            options={'permissions': (('can_change_author', 'Can change collection author'),)},
        ),
    ]
