# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-08 12:17
from __future__ import unicode_literals

from django.db import migrations


def copy_moderation_request_data(apps, schema_editor):
    confirmation_form_submission = apps.get_model('djangocms_moderation', 'ConfirmationFormSubmission')
    moderation_request_action = apps.get_model('djangocms_moderation', 'ModerationRequestAction')

    for model_class in (confirmation_form_submission, moderation_request_action):
        for obj in model_class.objects.all():
            obj.moderation_request = obj.request
            obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0009_auto_20181005_1534'),
    ]

    operations = [
        migrations.RunPython(copy_moderation_request_data),
    ]
