# Generated by Django 1.11.15 on 2019-03-13 16:38
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0013_auto_20181122_1110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=120, unique=True, verbose_name='name'),
        ),
    ]
