# Generated by Django 1.11.15 on 2019-03-15 17:23
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0014_auto_20190313_1638'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcollection',
            options={'permissions': (
                ('can_change_author', 'Can change collection author'),
                ('cancel_moderationcollection', 'Can cancel collection')
                ),
                'verbose_name': 'collection'
            },
        ),
    ]
