# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-27 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0014_moderationrequesttreenode'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationrequesttreenode',
            options={'ordering': ('id',)},
        ),
    ]
