# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-10-11 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0016_moderationrequesttreenode'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='is_unpublishing',
            field=models.BooleanField(default=False, verbose_name='unpublishing workflow'),
        ),
    ]
