# Generated by Django 2.2.24 on 2022-08-31 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0016_moderationrequesttreenode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moderationrequest',
            name='language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('ja', 'Japanese')], max_length=255, verbose_name='language'),
        )
    ]
