# Generated by Django 5.0.14 on 2025-08-05 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("djangocms_moderation", "0001_squashed_0017_auto_20220831_0727"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="workflow",
            options={
                "ordering": ("name",),
                "verbose_name": "Workflow",
                "verbose_name_plural": "Workflows",
            },
        ),
        migrations.AlterField(
            model_name="moderationrequest",
            name="language",
            field=models.CharField(
                choices=[("de", "German"), ("en", "English")],
                max_length=20,
                verbose_name="language",
            ),
        ),
        migrations.AlterField(
            model_name="workflow",
            name="compliance_number_backend",
            field=models.CharField(
                choices=[
                    (
                        "djangocms_moderation.backends.uuid4_backend",
                        "Unique alphanumeric string",
                    ),
                    (
                        "djangocms_moderation.backends.sequential_number_backend",
                        "Sequential number",
                    ),
                    (
                        "djangocms_moderation.backends.sequential_number_with_identifier_prefix_backend",
                        "Sequential number with identifier prefix",
                    ),
                ],
                default="djangocms_moderation.backends.uuid4_backend",
                max_length=255,
                verbose_name="compliance number backend",
            ),
        ),
    ]
