# Generated by Django 5.2.18 on 2026-10-07 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djangocms_moderation', '0021_moderationrequesttreenode_parent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='moderationcollection',
            options={
                'permissions': (
                    ('can_change_author', 'Can change collection author'),
                    ('cancel_moderationcollection', 'Can cancel collection'),
                ),
                'verbose_name': 'collection',
                'verbose_name_plural': 'Collections',
            },
        ),
    ]
