# -*- coding: utf-8 -*-
# Generated by Django 1.11.12 on 2018-05-03 09:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aldryn_forms', '0011_auto_20180110_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModerationForm',
            fields=[
            ],
            options={
                'verbose_name': 'Moderation Form',
                'verbose_name_plural': 'Moderation Forms',
                'proxy': True,
                'indexes': [],
            },
            bases=('aldryn_forms.formplugin',),
        ),
    ]
