const babelParser = require('@babel/eslint-parser');
const compat = require('eslint-plugin-compat');
const globals = require('globals');

module.exports = [
    {
        ignores: [
            'djangocms_moderation/static/djangocms_moderation/js/dist/**',
            'djangocms_moderation/static/djangocms_moderation/js/libs/**',
        ],
    },
    compat.configs['flat/recommended'],
    {
        files: ['djangocms_moderation/static/djangocms_moderation/js/**/*.js'],
        languageOptions: {
            parser: babelParser,
            parserOptions: {
                requireConfigFile: false,
                sourceType: 'module',
                babelOptions: {
                    presets: ['@babel/preset-env'],
                },
            },
            globals: {
                ...globals.browser,
                ...globals.commonjs,
                ...globals.jquery,
                ...globals.jasmine,
                CMS: 'readonly',
                django: 'readonly',
            },
        },
        rules: {
            'no-cond-assign': 'error',
            'no-console': 'warn',
            'no-constant-condition': 'error',
            'no-control-regex': 'error',
            'no-debugger': 'error',
            'no-dupe-args': 'error',
            'no-dupe-keys': 'error',
            'no-duplicate-case': 'error',
            'no-empty-character-class': 'error',
            'no-empty': ['error', { allowEmptyCatch: true }],
            'no-ex-assign': 'error',
            'no-extra-boolean-cast': 'error',
            'no-extra-semi': 'error',
            'no-func-assign': 'error',
            'no-inner-declarations': 'error',
            'no-invalid-regexp': 'error',
            'no-irregular-whitespace': 'error',
            'no-unsafe-negation': 'error',
            'no-obj-calls': 'error',
            'no-regex-spaces': 'error',
            'no-sparse-arrays': 'error',
            'no-unexpected-multiline': 'error',
            'no-unreachable': 'error',
            'use-isnan': 'error',
            'valid-typeof': 'error',

            'accessor-pairs': 'error',
            'block-scoped-var': 'error',
            curly: 'error',
            'default-case': 'error',
            'dot-notation': 'error',
            eqeqeq: 'error',
            'guard-for-in': 'error',
            'no-alert': 'error',
            'no-caller': 'error',
            'no-case-declarations': 'error',
            'no-div-regex': 'error',
            'no-else-return': 'warn',
            'no-empty-pattern': 'error',
            'no-eq-null': 'error',
            'no-eval': 'error',
            'no-extend-native': 'error',
            'no-extra-bind': 'error',
            'no-fallthrough': 'error',
            'no-floating-decimal': 'error',
            'no-implied-eval': 'error',
            'no-iterator': 'error',
            'no-labels': 'error',
            'no-lone-blocks': 'error',
            'no-loop-func': 'error',
            'no-multi-spaces': 'error',
            'no-global-assign': 'error',
            'no-new-func': 'error',
            'no-new-wrappers': 'error',
            'no-octal-escape': 'error',
            'no-octal': 'error',
            'no-proto': 'error',
            'no-redeclare': 'error',
            'no-return-assign': 'error',
            'no-script-url': 'error',
            'no-self-compare': 'error',
            'no-sequences': 'error',
            'no-throw-literal': 'error',
            'no-unused-expressions': ['error', { allowShortCircuit: true }],
            'no-useless-call': 'error',
            'no-useless-concat': 'error',
            'no-void': 'error',
            'no-with': 'error',
            radix: 'error',
            'wrap-iife': ['error', 'inside'],
            yoda: ['error', 'never', { exceptRange: true }],

            'no-delete-var': 'error',
            'no-label-var': 'error',
            'no-shadow-restricted-names': 'error',
            'no-shadow': 'error',
            'no-undef-init': 'error',
            'no-undef': 'error',
            'no-unused-vars': ['error', { caughtErrors: 'none' }],
            'no-use-before-define': 'error',

            'compat/compat': 'error',
        },
    },
];
