[tox]
envlist =
    ruff
    isort
    py{310,311,312}-dj52-cms{41,50,51}

skip_missing_interpreters=True

[testenv]
deps =
    cms41: -r{toxinidir}/tests/requirements/dj52_cms41.txt
    cms50: -r{toxinidir}/tests/requirements/dj52_cms50.txt
    cms51: -r{toxinidir}/tests/requirements/dj52_cms51.txt

basepython =
    py310: python3.10
    py311: python3.11
    py312: python3.12

commands =
    {envpython} --version
    {env:COMMAND:coverage} erase
    {env:COMMAND:coverage} run -m pytest
    {env:COMMAND:coverage} report

[testenv:ruff]
basepython = python3.12
commands = ruff check
deps = ruff

[testenv:isort]
basepython = python3.12
commands = isort --check-only --diff {toxinidir}
deps = isort
